[package]
name = "ethernetxpansion-driver"
repository = "https://github.com/las-vejas/ethernetxpansion"
description = "A driver for the ethernetxpansion module (WIZnet W5500)."
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
xpanse-api = "0.2.3"
embassy-rp = "0.10.0"
embassy-time = "0.5"
embassy-net-wiznet = "0.3"
embedded-hal-bus = { version = "0.3", features = ["async"] }
